### ISSUE TITLE
Feature request: running multiple profiles side by side

### ISSUE THREAD

**Issue by mio-19** [lateautumn233/Linuxdeploy-Pro#10]
Currently profiles share a common mount point, making running multiple profiles impossible.
Actually starting another profile will currently result in linuxdeploy reporting that paths were mounted, which is a bug

**Comment by lateautumn233** [comment]
这是因为Linuxdepoly方便管理会挂载rootfs或者目录到CHROOT_DIR /data/local/mnt 然后在chroot
也许可以将PROFILE追加到CHROOT_DIR
