### ISSUE TITLE
一直输出I: retrieving inrelease

### ISSUE THREAD

**Issue by RizzoHou** [lateautumn233/Linuxdeploy-Pro#24]
![Screenshot_2023-07-21-12-00-10-68_122326.png](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/79202911/d243d29a-b729-4f52-92d5-3fc1e1be1153)

我在安装kali, 手机网络良好，无代理。安装时一直卡在retrieving inrelease这里

**Comment by RizzoHou** [comment]
![Screenshot_2023-07-21-12-27-19-71_122748.png](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/79202911/0460af90-1753-44eb-a57b-5290222d7ba8)

**Comment by RizzoHou** [comment]
安装源我还换过清华源和官方源，也都不行

**Comment by RizzoHou** [comment]
也不光是kali有问题，我安装ubuntu时也不行

**Comment by RizzoHou** [comment]
![IMG_20230721_123435.jpg](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/79202911/cd780be4-52e1-4278-bdea-6e3f51c01a32)

手机配置

**Comment by RizzoHou** [comment]
我用我安卓13的新手机可以安装，用旧手机试不行

**Comment by lateautumn233** [comment]
请设置勾选全部调试选项并发log文件

**Comment by RizzoHou** [comment]
通过百度网盘分享的文件：output_0…
链接:https://pan.baidu.com/s/13zoCiz_Hv4mlasXEeTtSUw?pwd=d8t4 
提取码:d8t4
复制这段内容打开「百度网盘APP 即可获取」
文件有点大，在文本的较后位置，可以看到我说的那个问题

**Comment by lateautumn233** [comment]
安装目录的/data/local/mnt/deboostrap.log发一下

**Comment by RizzoHou** [comment]
我这里mnt文件夹底下是空的

**Comment by lateautumn233** [comment]
> 我这里mnt文件夹底下是空的

重新安装一次Linux在到目录里面找相关文件

**Comment by RizzoHou** [comment]
当安装程序在retrieving inrelease卡住时，我到你之前说的文件夹里面去看了一下，还是没有这个日志文件

**Comment by RizzoHou** [comment]
抱歉，我现在才看到，你说的安装目录是什么意思？它指的是哪个目录？

**Comment by RizzoHou** [comment]
我刚刚是在安卓的根目录下查看的

**Comment by lateautumn233** [comment]
用目录安装，然后发安装目录下的log

**Comment by RizzoHou** [comment]
用目录安装的话，旧手机直接重启

**Comment by RizzoHou** [comment]
没有创建任何文件夹

**Comment by lateautumn233** [comment]
无可用log无法修复
