### ISSUE TITLE
README.md "The app is available for download in Google Play and GitHub" but I can't find it on Google Play

### ISSUE THREAD

**Issue by ScottRFrost** [lateautumn233/Linuxdeploy-Pro#29]
In the US Google Play store, I can find the old (hasn't been updated since 2020) LinuxDeploy, but not LinuxDeploy-Pro

https://play.google.com/store/search?q=LinuxDeploy%20Pro&c=apps

**Comment by lateautumn233** [comment]
This is my personal project and has not been listed on Google Play

**Comment by bonswouar** [comment]
Well you might want to update the README then
