### ISSUE TITLE
Add Proot Container Adaptation

### ISSUE THREAD

**Issue by PangBaiWork** [lateautumn233/Linuxdeploy-Pro#31]
In fact, there was a proot option in Linuxdeploy before.But for some reason it was removed.One of the reasons is the permission issue with tar in busybox(Busybox creates decompression folder logic that is not suitable for non root situations).I fixed this issue by modifying busybox. Another issue is the issue of hard links during decompression, which can be solved by Proot(--link2symlink).But there are still other issues here, for example, updating configuration files and desktops, etc.
If possible, I hope you can add proot for Linuxdeploy cli. In fact, I have almost solved the bootstraps building,But there are still some other aspects that need improvement.You can take a look at my project [Dowork](https://github.com/PangBaiWork/Dowork)
I am not very familiar with shell and look forward to your help

**Comment by lateautumn233** [comment]
You can contact me via email or tg
