### ISSUE TITLE
Always displays "retrieving inrelease" during installation

### ISSUE THREAD

**Issue by tiehu** [lateautumn233/Linuxdeploy-Pro#32]
I'm not sure if it's the same as the feedback in #24.

I checked the debootstrap.log in the installation path and noticed that the log only repeatedly outputs the following message:
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__freading" referenced by "/data/data/ru.meefik.linuxdeploy/files/bin/wget"...

My device is root and has been granted the Linux Deploy root permission.

I have tried to switch to other mirror sites and have confirmed that my network environment can access them.

I have tried reinstalling Linux and Linux Deploy.

**Comment by lateautumn233** [comment]
Thank you for your feedback. I will be available when I have time

**Comment by tiehu** [comment]
I have verified that this is caused by busybox, updating busybox can solve the problem:

https://github.com/meefik/busybox

**Comment by lateautumn233** [comment]
> I have verified that this is caused by busybox, updating busybox can solve the problem:
> 
> https://github.com/meefik/busybox

But I use GNUwget

**Comment by tiehu** [comment]
> > I have verified that this is caused by busybox, updating busybox can solve the problem:
> > https://github.com/meefik/busybox
> 
> But I use GNUwget

I may be mistaken, but I checked /dat/data/ru.meefik.linuxdeploy/files/bin and found that the wget file was actually linked to busybox binary file.

I tested on ARM64, using version 3.1.0.

**Comment by tiehu** [comment]
I cloned the dev branch, updated busybox, and recompiled a version. Then I noticed that the bug didn't reappear.

**Comment by Chanhnh** [comment]
> Tôi đã nhân bản nhánh dev, cập nhật busybox và biên dịch lại một phiên bản. Sau đó tôi nhận thấy rằng lỗi không xuất hiện trở lại.

Good job bro, fix and working on Android 7.1.2

**Comment by lateautumn233** [comment]
https://github.com/lateautumn233/Linuxdeploy-Pro/suites/18453389941/artifacts/1070079215
