### ISSUE TITLE
挂载的安卓文件夹在哪里？

### ISSUE THREAD

**Issue by RizzoHou** [lateautumn233/Linuxdeploy-Pro#45]
![Screenshot_2024-02-08-11-28-17-807_ru.meefik.linuxdeploy.jpg](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/79202911/ca6d776d-4646-4aa3-94c6-4e1130c05d25)

**Comment by kmiit** [comment]
默认位置不清楚，不过可以自定义挂载的目标目录

**Comment by RizzoHou** [comment]
我试过自定义,但在我自定义的位置上找不到

**Comment by RizzoHou** [comment]
![Screenshot_2024-02-08-12-57-55-679_ru.meefik.linuxdeploy.jpg](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/79202911/2deebd62-e132-479b-b0e5-c996fe6e7486)

![Screenshot_2024-02-08-12-57-44-777_ru.meefik.linuxdeploy.jpg](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/79202911/87366d07-afac-4042-97f2-9e6406c3421c)

可以用上面的方式自定义吗？

**Comment by kmiit** [comment]
是啊
![Uploading Screenshot_2024-02-08-12-58-37-402_ru.meefik.linuxdeploy.jpg…]()

**Comment by kmiit** [comment]
是啊
![Screenshot_2024-02-08-12-58-37-402_ru meefik linuxdeploy](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/61952405/cd3f09d5-bfdc-4ea8-868c-03c52339697c)
![Screenshot_2024-02-08-12-58-27-433_bin mt plus](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/61952405/bb7f5323-8957-4e3f-83bd-a194b5dd4ff4)
![Screenshot_2024-02-08-12-58-20-508_com termux](https://github.com/lateautumn233/Linuxdeploy-Pro/assets/61952405/0efcdcee-f9d0-4cbb-9f96-4f299c19bb8a)

**Comment by RizzoHou** [comment]
又试过了，还是不太行

**Comment by RizzoHou** [comment]
是需要安装系统时就配置好吗

**Comment by kmiit** [comment]
> 是需要安装系统时就配置好吗

不用啊，你下最新的ci试试

**Comment by xiangxiangxiong9** [comment]
看看 启动[>>>start] 的时候有没有显示 `Mounting partitions` 什么的
如果没有 - 看看 `属性`  里 `容器类型` 是 `chroot` 还是 `unshare`
> 如果是 `unshare`
>> 改成 `chroot`

**Comment by xiangxiangxiong9** [comment]
试一下最新的CI构建
> 如果不行
>> 看看 `容器类型` 是 `chroot` 还是 `unshare`
>> 如果是 `unshare`
>>> 尝试 `设置 - 环境 - 更新环境`

**Comment by lateautumn233** [comment]
log
