### ISSUE TITLE
SSH not Starting

### ISSUE THREAD

**Issue by pcamposu** [lateautumn233/Linuxdeploy-Pro#46]
[output.log](https://github.com/lateautumn233/Linuxdeploy-Pro/files/14336673/output.log)

**Comment by ghost** [comment]
+ chroot /data/local/mnt /bin/su - root -c '/usr/sbin/sshd -p 22'
chroot: exec /bin/su: No such file or directory
+ is_ok fail done
+ '[' 127 -eq 0 ']'
+ '[' -n fail ']'
fail
+ msg fail
+ echo fail
+ return 1
+ return 0
+ set -e
From the screenshots of the part of the log about startup ssh, it seems that rootfs is wrong. If you're installing it online, your debootstrap build process must have failed; If you are importing offline rootfs, then your tar package is corrupted.
