### ISSUE TITLE
about iptables in chroot (want help)

### ISSUE THREAD

**Issue by wumulong-469** [lateautumn233/Linuxdeploy-Pro#59]
## inuxdeploy git-commit：9f51b60718ffd800abe8a873c7e8973dbddebf1f
🤔在chroot 中，无法“指定”更改和删除iptables的过滤规则。但是可以添加规则，和执行iptables -F 删除所有规则。unchroot使用iptables没有任何问题。
![image](https://github.com/user-attachments/assets/085eeb20-b015-4855-b129-89cfc2cc3e28)

**Comment by wumulong-469** [comment]
chroot env : alpine-v3.18, 据尝试kali也一样复现。

**Comment by lateautumn233** [comment]
chroot问题无解
