### ISSUE TITLE
Add Chinese README

### ISSUE THREAD

**Issue by ghost** [lateautumn233/Linuxdeploy-Pro#9]
建议添加中文说明

**Comment by lateautumn233** [comment]
PR Please

**Comment by ghost** [comment]
Add it to weblate please.
I can hardly use git because of my poor dev skill.

**Comment by ghost** [comment]
I didn't find good ways to add Chinese README.
Maybe add README_zh.md ?

**Comment by lateautumn233** [comment]
https://zh.crowdin.com/project/Linux-Deploy
please

**Comment by ghost** [comment]
crowdin和weblate不会冲突吗？

**Comment by lateautumn233** [comment]
> crowdin和weblate不会冲突吗？

理论上不会

**Comment by ghost** [comment]
哦我明白了这两个是需要手动设定需要翻译的文件

**Comment by ghost** [comment]
已经开始搞了

**Comment by ghost** [comment]
别忘了删掉我标记的段落！
